#!/bin/bash

echo "Instalando gems..."
docker run \
  --rm \
  -v rubygems:/usr/local/bundle/ \
  ruby \
  bash -c "gem install rspec pg rake rack sinatra puma" && echo "Gems instaladas com sucesso!"
